apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: rapid-1
  namespace: toi
  labels:
    team: toi
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "false"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 336
  acl:
    - team: toi
      application: toi-cv
      access: readwrite
    - team: toi
      application: toi-arbeidsmarked-cv
      access: readwrite
    - team: toi
      application: toi-veileder
      access: readwrite
    - team: toi
      application: toi-oppfolgingsinformasjon
      access: readwrite
    - team: toi
      application: toi-siste-14a-vedtak
      access: readwrite
    - team: toi
      application: toi-oppfolgingsperiode
      access: readwrite
    - team: toi
      application: toi-sammenstille-kandidat
      access: readwrite
    - team: toi
      application: toi-kandidatfeed
      access: readwrite
    - team: toi
      application: toi-identmapper
      access: readwrite
    - team: toi
      application: toi-fritatt-kandidatsok
      access: readwrite
    - team: toi
      application: toi-synlighetsmotor
      access: readwrite
    - team: toi
      application: toi-hjemmel
      access: readwrite
    - team: toi
      application: toi-kafkamanager
      access: readwrite
    - team: toi
      application: toi-maa-behandle-tidligere-cv
      access: readwrite
    - team: toi
      application: toi-organisasjonsenhet
      access: readwrite
    - team: toi
      application: toi-tilretteleggingsbehov
      access: readwrite
    - team: toi
      application: toi-helseapp
      access: readwrite
    - team: toi
      application: toi-hull-i-cv
      access: readwrite
    - team: toi
      application: rekrutteringsbistand-kandidat-api
      access: write
    - team: arbeidsgiver-inkludering
      application: foresporsel-om-deling-av-cv-api
      access: readwrite
    - team: toi
      application: rekrutteringsbistand-statistikk-api
      access: readwrite
    - team: toi
      application: rekrutteringsbistand-stilling-api
      access: readwrite
    - team: toi
      application: presenterte-kandidater-api
      access: readwrite
    - team: toi
      aplication: toi-ontologitjeneste
      access: readwrite
