apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-fritatt-kandidatsok
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-fritatt-kandidatsok
      rules:
        - alert: toi-fritatt-kandidatsok
          expr: kube_deployment_status_replicas_available{deployment="toi-fritatt-kandidatsok"} == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/goto/3f6e0ef0-64e1-11ed-9d6c-8305350409f6"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-fritatt-kandidatsok
          expr: sum(increase(log_messages_errors{app="toi-fritatt-kandidatsok", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/goto/3f6e0ef0-64e1-11ed-9d6c-8305350409f6"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-fritatt-kandidatsok
          expr: sum(increase(log_messages_errors{app="toi-fritatt-kandidatsok", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/goto/3f6e0ef0-64e1-11ed-9d6c-8305350409f6"
          labels:
            namespace: toi
            severity: warning
