apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-hjemmel
  namespace: toi
  labels:
    team: toi

spec:
  groups:
    - name: toi-hjemmel
      rules:
        - alert: toi-hjemmel
          expr: kube_deployment_status_replicas_available{deployment="toi-hjemmel"} == 0
          for: 2m
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.adeo.no/app/r/s/zrHA2"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-hjemmel
          expr: sum(increase(log_messages_errors{app="toi-hjemmel", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.adeo.no/app/r/s/zrHA2"
          labels:
            namespace: toi
            severity: danger

        - alert: toi-hjemmel
          expr: sum(increase(log_messages_errors{app="toi-hjemmel", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warning
            action: "https://logs.adeo.no/app/r/s/zrHA2"
          labels:
            namespace: toi
            severity: warning
