apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-helseapp
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-helseapp
      rules:
        - alert: toi-helseapp
          expr: kube_deployment_status_replicas_available{deployment="toi-helseapp"} == 0
          for: 10s
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.adeo.no/goto/2d965f50-0db3-11ed-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-helseapp
          expr: sum(increase(log_messages_errors{app="toi-helseapp", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.adeo.no/goto/2d965f50-0db3-11ed-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-helseapp
          expr: sum(increase(log_messages_errors{app="toi-helseapp", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/goto/2d965f50-0db3-11ed-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: warning
