apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-ontologitjeneste
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-ontologitjeneste
      rules:
        - alert: toi-ontologitjeneste
          expr: kube_deployment_status_replicas_available{deployment="toi-ontologitjeneste"} == 0
          for: 10s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/02nZX"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-ontologitjeneste
          expr: sum(increase(log_messages_errors{app="toi-ontologitjeneste", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/02nZX"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-ontologitjeneste
          expr: sum(increase(log_messages_errors{app="toi-ontologitjeneste", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/02nZX"
          labels:
            namespace: toi
            severity: warning
