apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-identmapper
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: identmapping-db
  azure:
    application:
      enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: PDL_SCOPE
      value: {{ pdl_scope }}
    - name: PDL_URL
      value: {{ pdl_url }}
