apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-sammenstille-kandidat
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 9000
  ingresses:
    - {{ ingress }}
  liveness:
    port: 8080
    path: /isalive
  readiness:
    port: 8080
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
    port: "8080"
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
        databases:
          - name: db
  azure:
    application:
      enabled: true
  envFrom:
    - secret: passord-for-republisering
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
