apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-synlighetsmotor
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-synlighetsmotor
      rules:
        - alert: toi-synlighetsmotor
          expr: kube_deployment_status_replicas_available{deployment="toi-synlighetsmotor"} == 0
          for: 10s
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.adeo.no/goto/cf3fc1b0-43bf-11ed-8607-d590fd125f80"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-synlighetsmotor
          expr: sum(increase(log_messages_errors{app="toi-synlighetsmotor", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.adeo.no/goto/cf3fc1b0-43bf-11ed-8607-d590fd125f80"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-synlighetsmotor
          expr: sum(increase(log_messages_errors{app="toi-synlighetsmotor", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/goto/cf3fc1b0-43bf-11ed-8607-d590fd125f80"
          labels:
            namespace: toi
            severity: warning
