apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-synlighetsmotor
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8301
  ingresses:
    - {{ ingress }}
  liveness:
    path: /isalive
  readiness:
    port: 8080
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
    port: "8080"
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{ ad_gruppe_modia_generell_tilgang }}
          - id: {{ ad_gruppe_modia_oppfølging }}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
        databases:
          - name: synlighetsmotor-db
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-container
          cluster: {{ cluster }}
          namespace: toi
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"