apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-synlighetsmotor
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: synlighetsmotor-db
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"