name: toi-hjemmel

on:
  push:
    paths:
    - apps/toi-hjemmel/**
    - .github/workflows/deploy-toi-hjemmel.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/vis-appnavn-i-trivyrapporten
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
