name: toi-arbeidsgiver-notifikasjon

on:
  push:
    paths:
    - apps/toi-arbeidsgiver-notifikasjon/**
    - .github/workflows/deploy-toi-arbeidsgiver-notifikasjon.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app-name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/foobar
    secrets: inherit
