on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      deploy_dev_branch:
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java v17.x
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: Gradle test and build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew :apps:${{ inputs.app_name }}:test :apps:${{ inputs.app_name }}:build
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: toi
          image_suffix: ${{ inputs.app_name }}
          dockerfile: apps/${{ inputs.app_name }}/Dockerfile
          docker_context: apps/${{ inputs.app_name }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          # The tag "latest" should only be applied to images based on the default branch
          tag: ${{ contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && 'latest' || github.sha }}

  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    needs: build-and-publish
    if: github.ref == 'refs/heads/main' || github.ref == inputs.deploy_dev_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ inputs.app_name }}/nais.yaml
          VARS: apps/${{ inputs.app_name }}/nais-dev.yaml
          VAR: image=${{ needs.build-and-publish.outputs.image }}

  deploy-to-prod-gcp:
    name: Deploy to prod-gcp
    needs: [build-and-publish, deploy-to-dev-gcp]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/${{ inputs.app_name }}/nais.yaml,apps/${{ inputs.app_name }}/alerts.yaml
          VARS: apps/${{ inputs.app_name }}/nais-prod.yaml
          VAR: image=${{ needs.build-and-publish.outputs.image }}
