name: toi-synlighetsmotor

on:
  push:
    paths:
    - apps/toi-synlighetsmotor/**
    - .github/workflows/deploy-toi-synlighetsmotor.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/auditlogging-synlighet
    secrets: inherit