name: toi-helseapp

env:
  APP_NAME: ${{ github.workflow }}

on:
  push:
    branches:
    - main
    paths:
    - apps/toi-helseapp/**
    - .github/workflows/deploy-toi-helseapp.yaml
    - buildSrc/**

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build, test, and publish
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java v17.x
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: Gradle test and build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew :apps:${APP_NAME}:test :apps:${APP_NAME}:build
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: toi
          image_suffix: ${{ inputs.app_name }}
          dockerfile: apps/${{ inputs.app_name }}/Dockerfile
          docker_context: apps/${{ inputs.app_name }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
          build_args: |
            APP_NAME=${{ inputs.app_name }}

  deploy-to-prod-gcp:
    name: Deploy to prod-gcp
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/${{ env.APP_NAME }}/nais.yaml,apps/${{ env.APP_NAME }}/alerts.yaml
          VAR: image=${{ needs.build-and-publish.outputs.image }}

  call-trivy-security-scan:
    needs: build-and-publish
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@main
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
    permissions:
      id-token: write
      security-events: write
    secrets: inherit
