name: toi-sammenstille-kandidat

on:
  push:
    paths:
    - apps/toi-sammenstille-kandidat/**
    - .github/workflows/deploy-toi-sammenstille-kandidat.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/vekk-fra-fork
    secrets: inherit