name: toi-arbeidsgiver-notifikasjon

on:
  push:
    paths:
    - apps/toi-arbeidsgiver-notifikasjon/**
    - .github/workflows/deploy-toi-arbeidsgiver-notifikasjon.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/foobar
    secrets: inherit
    permissions:
      id-token: write
      security-events: write
