name: Snyk monitor
on:
  push:
    branches:
      - main
      - test-sub-projects-snyk
jobs:
  snyk-monitor-monorepo:
    name: Monitor dependencies in monorepo with Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: monitor
          args: --org=toi --all-sub-projects --remote-repo-url=https://github.com/${{ github.repository }}.git
