name: Vulnerabilities scanning of dependencies using Snyk
on:
  push:
    branches:
      - main
jobs:
  app-dependencies-vulnerabilities-scanning:
    name: Monitor dependencies with Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java v17.x
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=toi --all-projects --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git