name: Snyk monitor
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/snyk.yaml
      - buildSrc/**

jobs:
  snyk-monitor-buildSrc:
    name: Monitor dependencies in buildSrc with Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=toi --file=buildSrc/build.gradle.kts --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git
